### ISSUE TITLE
<built-in function duplicated_object> returned a result with an error set

### ISSUE THREAD

**Issue by iamkucuk** [jmrichardson/tuneta#10]
Hi, and once again, thanks for this great work!

I encounter an error and wanted to discuss if this is a bug or I'm not using this library as intended. I'm running it via a Jupyter kernel. Here is my driver code:
```
#%%

import pandas as pd
import pandas_ta as ta
from sklearn.model_selection import train_test_split
from tuneta.tune_ta import TuneTA

#%%

X = pd.read_parquet('D:\data\\finance\candle\BTC-USDT.parquet').loc['2021-1-1':].iloc[:, :5]
y = ta.percent_return(X.close, offset=-1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, shuffle=False)

#%%
tt = TuneTA(verbose=True)
tt.fit(X_train, y_train,
    indicators=['pta.rsi'],
    trials=10,
    early_stop=100,
)
```

Running this gives me an error at the end with this traceback:

```
RemoteTraceback                           Traceback (most recent call last)

RemoteTraceback: 
"""
TypeError: unhashable type: 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\multiprocess\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\tuneta\optimize.py", line 178, in fit
    trials = trials[~trials.params.duplicated(keep='first')]
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\pandas\core\series.py", line 2034, in duplicated
    res = base.IndexOpsMixin.duplicated(self, keep=keep)
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\pandas\core\base.py", line 1302, in duplicated
    return duplicated(self._values, keep=keep)
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\pandas\core\algorithms.py", line 900, in duplicated
    return f(values, keep=keep)
SystemError: <built-in function duplicated_object> returned a result with an error set
"""


The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)

~\AppData\Local\Temp/ipykernel_2116/4239046016.py in <module>
      3     indicators=['pta.rsi'],
      4     trials=10,
----> 5     early_stop=100,
      6 )

~\miniconda3\envs\finance\lib\site-packages\tuneta\tune_ta.py in fit(self, X, y, trials, indicators, ranges, early_stop)
    121 
    122         # Blocking wait to retrieve results
--> 123         self.fitted = [fit.get() for fit in self.fitted]
    124 
    125         # Fits must contain best trial data

~\miniconda3\envs\finance\lib\site-packages\tuneta\tune_ta.py in <listcomp>(.0)
    121 
    122         # Blocking wait to retrieve results
--> 123         self.fitted = [fit.get() for fit in self.fitted]
    124 
    125         # Fits must contain best trial data

~\miniconda3\envs\finance\lib\site-packages\multiprocess\pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

SystemError: <built-in function duplicated_object> returned a result with an error set
```

**Comment by jmrichardson** [comment]
Hi  thanks for reporting the issue.  Your code looks good.  Can you share the results from the trials to make sure they are completing successfully. You should see output something like:

```
[I 2021-10-03 09:33:02,182] A new study created in memory with name: tta.RSI(X.close, timeperiod=trial.suggest_int('timeperiod', 2, 30), )
[I 2021-10-03 09:33:02,199] Trial 0 finished with value: 0.23400076346067003 and parameters: {'timeperiod': 22}. Best is trial 0 with value: 0.23400076346067003.
[I 2021-10-03 09:33:02,210] Trial 1 finished with value: 0.22793217963508575 and parameters: {'timeperiod': 10}. Best is trial 0 with value: 0.23400076346067003.
[I 2021-10-03 09:33:02,223] Trial 2 finished with value: 0.22100492791234747 and parameters: {'timeperiod': 8}. Best is trial 0 with value: 0.23400076346067003.
[I 2021-10-03 09:33:02,235] Trial 3 finished with value: 0.2345171320497095 and parameters: {'timeperiod': 17}. Best is trial 3 with value: 0.2345171320497095.
[I 2021-10-03 09:33:02,253] Trial 4 finished with value: 0.23400076346067003 and parameters: {'timeperiod': 22}. Best is trial 3 with value: 0.2345171320497095.
[I 2021-10-03 09:33:02,272] Trial 5 finished with value: 0.23341541015568376 and parameters: {'timeperiod': 14}. Best is trial 3 with value: 0.2345171320497095.
[I 2021-10-03 09:33:02,285] Trial 6 finished with value: 0.23174264411557063 and parameters: {'timeperiod': 30}. Best is trial 3 with value: 0.2345171320497095.
[I 2021-10-03 09:33:02,299] Trial 7 finished with value: 0.23363005652078525 and parameters: {'timeperiod': 21}. Best is trial 3 with value: 0.2345171320497095.
[I 2021-10-03 09:33:02,313] Trial 8 finished with value: 0.23410549751701554 and parameters: {'timeperiod': 15}. Best is trial 3 with value: 0.2345171320497095.
```

The only other two variables I can think of are your dataset and the versions of the packages required for tuneta.  If the trials are successful like above, then would like to get your dataset(just a portion) and the version information of the packages.  I am happy to debug what happened but can't reproduce with the data I am using.

**Comment by iamkucuk** [comment]
The outputs are showing. Here is the full output: 

```
[I 2021-10-03 16:12:59,255] A new study created in memory with name: pta.rsi(X.close, length=trial.suggest_int('length', 3, 180), scalar=trial.suggest_int('scalar', 3, 180), )
[I 2021-10-03 16:14:51,854] Trial 0 finished with value: 0.10030315751331827 and parameters: {'length': 126, 'scalar': 53}. Best is trial 0 with value: 0.10030315751331827.
[I 2021-10-03 16:16:44,802] Trial 1 finished with value: 0.08849655544588059 and parameters: {'length': 43, 'scalar': 101}. Best is trial 0 with value: 0.10030315751331827.
[I 2021-10-03 16:18:37,069] Trial 2 finished with value: 0.10065897379158083 and parameters: {'length': 131, 'scalar': 78}. Best is trial 2 with value: 0.10065897379158083.
[I 2021-10-03 16:20:30,250] Trial 3 finished with value: 0.10332699219470969 and parameters: {'length': 177, 'scalar': 124}. Best is trial 3 with value: 0.10332699219470969.
[I 2021-10-03 16:22:23,322] Trial 4 finished with value: 0.09667967173283709 and parameters: {'length': 88, 'scalar': 72}. Best is trial 3 with value: 0.10332699219470969.
[I 2021-10-03 16:24:15,833] Trial 5 finished with value: 0.09310051424587355 and parameters: {'length': 64, 'scalar': 132}. Best is trial 3 with value: 0.10332699219470969.
[I 2021-10-03 16:26:08,320] Trial 6 finished with value: 0.09577386949320228 and parameters: {'length': 81, 'scalar': 13}. Best is trial 3 with value: 0.10332699219470969.
[I 2021-10-03 16:28:01,327] Trial 7 finished with value: 0.09460813347210287 and parameters: {'length': 73, 'scalar': 134}. Best is trial 3 with value: 0.10332699219470969.
[I 2021-10-03 16:29:54,009] Trial 8 finished with value: 0.08604682948025838 and parameters: {'length': 35, 'scalar': 34}. Best is trial 3 with value: 0.10332699219470969.
[I 2021-10-03 16:31:46,381] Trial 9 finished with value: 0.09772714793663073 and parameters: {'length': 97, 'scalar': 97}. Best is trial 3 with value: 0.10332699219470969.
multiprocess.pool.RemoteTraceback: 
"""
TypeError: unhashable type: 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\multiprocess\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\tuneta\optimize.py", line 178, in fit
    trials = trials[~trials.params.duplicated(keep='first')]
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\pandas\core\series.py", line 2034, in duplicated
    res = base.IndexOpsMixin.duplicated(self, keep=keep)
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\pandas\core\base.py", line 1302, in duplicated
    return duplicated(self._values, keep=keep)
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\pandas\core\algorithms.py", line 900, in duplicated
    return f(values, keep=keep)
SystemError: <built-in function duplicated_object> returned a result with an error set
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Furkan\Documents\Projects\sjgsfinance\candle_indicator_experiments\optimize_indicators.py", line 20, in <module>
    roll()
  File "C:\Users\Furkan\Documents\Projects\sjgsfinance\candle_indicator_experiments\optimize_indicators.py", line 15, in roll
    early_stop=100,
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\tuneta\tune_ta.py", line 123, in fit
    self.fitted = [fit.get() for fit in self.fitted]
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\tuneta\tune_ta.py", line 123, in <listcomp>
    self.fitted = [fit.get() for fit in self.fitted]
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\multiprocess\pool.py", line 657, in get
    raise self._value
SystemError: <built-in function duplicated_object> returned a result with an error set

Process finished with exit code 1
```

**Comment by jmrichardson** [comment]
hmmm... I ran your code and it completed successfully:

```
[I 2021-10-03 09:57:11,911] A new study created in memory with name: pta.rsi(X.close, length=trial.suggest_int('length', 3, 180), scalar=trial.suggest_int('scalar', 3, 180), )
[I 2021-10-03 09:57:11,930] Trial 0 finished with value: 0.1652867329297138 and parameters: {'length': 126, 'scalar': 53}. Best is trial 0 with value: 0.1652867329297138.
[I 2021-10-03 09:57:11,945] Trial 1 finished with value: 0.222114355648157 and parameters: {'length': 43, 'scalar': 101}. Best is trial 1 with value: 0.222114355648157.
[I 2021-10-03 09:57:11,963] Trial 2 finished with value: 0.16326671192171832 and parameters: {'length': 131, 'scalar': 78}. Best is trial 1 with value: 0.222114355648157.
[I 2021-10-03 09:57:11,979] Trial 3 finished with value: 0.14438402174767295 and parameters: {'length': 177, 'scalar': 124}. Best is trial 1 with value: 0.222114355648157.
[I 2021-10-03 09:57:11,998] Trial 4 finished with value: 0.190642443534319 and parameters: {'length': 88, 'scalar': 72}. Best is trial 1 with value: 0.222114355648157.
[I 2021-10-03 09:57:12,013] Trial 5 finished with value: 0.21010270771398887 and parameters: {'length': 64, 'scalar': 132}. Best is trial 1 with value: 0.222114355648157.
[I 2021-10-03 09:57:12,033] Trial 6 finished with value: 0.19575367762517798 and parameters: {'length': 81, 'scalar': 13}. Best is trial 1 with value: 0.222114355648157.
[I 2021-10-03 09:57:12,050] Trial 7 finished with value: 0.20293519610192085 and parameters: {'length': 73, 'scalar': 134}. Best is trial 1 with value: 0.222114355648157.
[I 2021-10-03 09:57:12,073] Trial 8 finished with value: 0.22834288719109358 and parameters: {'length': 35, 'scalar': 34}. Best is trial 8 with value: 0.22834288719109358.
[I 2021-10-03 09:57:12,091] Trial 9 finished with value: 0.1835772292077892 and parameters: {'length': 97, 'scalar': 97}. Best is trial 8 with value: 0.22834288719109358.
Indicator Correlation to Target:
                               Correlation
---------------------------  -------------
pta_rsi_length_88_scalar_72       0.190642
Indicator Correlation to Each Other:
                               pta_rsi_length_88_scalar_72
---------------------------  -----------------------------
pta_rsi_length_88_scalar_72                              0
```

Does your dataset have a multiple index levels?  Also, what version of optuna and pandas are you using?  I will install those versions and test.

**Comment by iamkucuk** [comment]
pandas version: 1.2.4
optuna version: 2.9.1

Here is my dataframe index:
```
DatetimeIndex(['2021-01-01 00:00:00', '2021-01-01 00:01:00',
               '2021-01-01 00:02:00', '2021-01-01 00:03:00',
               '2021-01-01 00:04:00', '2021-01-01 00:05:00',
               '2021-01-01 00:06:00', '2021-01-01 00:07:00',
               '2021-01-01 00:08:00', '2021-01-01 00:09:00',
               ...
               '2021-08-06 23:50:00', '2021-08-06 23:51:00',
               '2021-08-06 23:52:00', '2021-08-06 23:53:00',
               '2021-08-06 23:54:00', '2021-08-06 23:55:00',
               '2021-08-06 23:56:00', '2021-08-06 23:57:00',
               '2021-08-06 23:58:00', '2021-08-06 23:59:00'],
              dtype='datetime64[ns]', name='open_time', length=313315, freq=None)
```
I can send the data I use too

**Comment by jmrichardson** [comment]
I was able to reproduce the problem with pandas 1.2.4.  Looking at the line of code causing the error:

            trials = trials[~trials.params.duplicated(keep='first')]

I assumed that the trials dataframe was somehow corrupted.  However, it looks fine:

![image](https://user-images.githubusercontent.com/6565528/135757852-af2fe5f2-e3f0-4fc2-ab9c-1f6d702f223a.png)

So, this looks like a bug with pandas when finding duplicates of dictionary values which is indicated in the error message:

`TypeError: unhashable type: 'dict'`

Can you upgrade to pandas 1.3.3 which is what I am using without any issues

**Comment by iamkucuk** [comment]
Now that's a bummer. Zipline and other couple of libraries I use was dependent on this pandas version. I will try to investigate this one further.

**Comment by jmrichardson** [comment]
@iamkucuk I updated the code to work with pandas 1.2.4 and hopefully any pandas version.  Install the latest with

`pip install -U git+https://github.com/jmrichardson/tuneta`

Let me know how it goes

**Comment by iamkucuk** [comment]
> 
> 
> @iamkucuk I updated the code to work with pandas 1.2.4 and hopefully any pandas version. Install the latest with
> 
> `pip install -U git+https://github.com/jmrichardson/tuneta`
> 
> Let me know how it goes

Instead, I opened a PR that resolves that issue (and probably removing overheads like string comparisons) with pandas series approach. Can you review it and see if it interferes with the logic of yours?
