### ISSUE TITLE
TypeError: Object of type Series is not JSON serializable error while saving res_y

### ISSUE THREAD

**Issue by iamkucuk** [jmrichardson/tuneta#13]
I encountered with an issue with my setup. I did solve the problem though, and will open a PR soon which resolves that possible issue. This issue is opened to be linked with the PR.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\optuna\trial\_trial.py", line 681, in set_user_attr
    self.storage.set_trial_user_attr(self._trial_id, key, value)
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\optuna\storages\_cached_storage.py", line 333, in set_trial_user_attr
    self._flush_trial(trial_id)
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\optuna\storages\_cached_storage.py", line 437, in _flush_trial
    datetime_complete=updates.datetime_complete,
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\optuna\storages\_rdb\storage.py", line 710, in _update_trial
    for k, v in user_attrs.items()
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\sqlalchemy\orm\collections.py", line 1276, in extend
    for value in iterable:
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\optuna\storages\_rdb\storage.py", line 711, in <genexpr>
    if k not in trial_user_attrs_dict
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Furkan\miniconda3\envs\finance\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
```

**Comment by jmrichardson** [comment]
Thanks for reporting the issue.  I haven't run into this issue so looking forward to the PR.
