### ISSUE TITLE
Optuna execution error of multiple pta indicators

### ISSUE THREAD

**Issue by QAQOAO** [jmrichardson/tuneta#15]
Well, after changing the code to my personal usage, I found that particularly some indicators of pandas-ta both have strange errors like my previous issue ：tos_stdevall, but the message is slightly different.

It seems to be a common error for pta.stochrsi, pta.tsi, pta.smi. Originally, I think it is an individual issue for one indicator. So I just drop it and rerun, but after I running “all” for three times, error of pta.stochrsi, pta.tsi, pta.smi came out sequentially. Afterwards, I think these errors might all have one thing in common. That is, when the indicator has multiple period parameters. So there might be more indicators with the error like below but not found by me yet. Hopefully you can solve  it soon, thanks again.

Below is the error message of pta.smi.

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 123, in _objective
    res = [eval_res(X, self.function, self.idx, trial, sym=sym) for sym, X in X.groupby(level=1)]
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 123, in <listcomp>
    res = [eval_res(X, self.function, self.idx, trial, sym=sym) for sym, X in X.groupby(level=1)]
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 98, in eval_res
    res = eval(function)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pandas_ta/momentum/smi.py", line 23, in smi
    tsi_df = tsi(close, fast=fast, slow=slow, signal=signal, scalar=scalar)
  File "/usr/local/lib/python3.7/dist-packages/pandas_ta/momentum/tsi.py", line 34, in tsi
    tsi_signal = ma(mamode, tsi, length=signal)
  File "/usr/local/lib/python3.7/dist-packages/pandas_ta/overlap/ma.py", line 73, in ma
    else: return ema(source, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pandas_ta/overlap/ema.py", line 22, in ema
    ema = EMA(close, length)
  File "/usr/local/lib/python3.7/dist-packages/talib/__init__.py", line 35, in wrapper
    result = func(*args, **kwargs)
  File "talib/_func.pxi", line 2931, in talib._ta_lib.EMA
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 189, in fit
    n_trials=self.n_trials, callbacks=[_early_stopping_opt])
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/study.py", line 409, in optimize
    show_progress_bar=show_progress_bar,
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 76, in _optimize
    progress_bar=progress_bar,
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 188, in <lambda>
    self.study.optimize(lambda trial: _objective(self, trial, X, y),
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 128, in _objective
    raise RuntimeError(f"Optuna execution error: {self.function}")
RuntimeError: Optuna execution error: pta.smi(X.close, fast=trial.suggest_int('fast', 2, 30), slow=trial.suggest_int('slow', 2, 30), signal=trial.suggest_int('signal', 2, 30), scalar=trial.suggest_int('scalar', 2, 30), )
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-16-de4150083369> in <module>()
      7     ranges=[(2, 30)],
      8     trials=100,
----> 9     early_stop=50,
     10 )
     11 

2 frames
/usr/local/lib/python3.7/dist-packages/multiprocess/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

RuntimeError: Optuna execution error: pta.smi(X.close, fast=trial.suggest_int('fast', 2, 30), slow=trial.suggest_int('slow', 2, 30), signal=trial.suggest_int('signal', 2, 30), scalar=trial.suggest_int('scalar', 2, 30), )

——————————————————————-

Below is the error message of pta.stochrsi

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 123, in _objective
    res = [eval_res(X, self.function, self.idx, trial, sym=sym) for sym, X in X.groupby(level=1)]
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 123, in <listcomp>
    res = [eval_res(X, self.function, self.idx, trial, sym=sym) for sym, X in X.groupby(level=1)]
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 98, in eval_res
    res = eval(function)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pandas_ta/momentum/stochrsi.py", line 30, in stochrsi
    stochrsi_d = ma(mamode, stochrsi_k, length=d)
  File "/usr/local/lib/python3.7/dist-packages/pandas_ta/overlap/ma.py", line 65, in ma
    elif name == "sma": return sma(source, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pandas_ta/overlap/sma.py", line 20, in sma
    sma = SMA(close, length)
  File "/usr/local/lib/python3.7/dist-packages/talib/__init__.py", line 35, in wrapper
    result = func(*args, **kwargs)
  File "talib/_func.pxi", line 4538, in talib._ta_lib.SMA
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 189, in fit
    n_trials=self.n_trials, callbacks=[_early_stopping_opt])
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/study.py", line 409, in optimize
    show_progress_bar=show_progress_bar,
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 76, in _optimize
    progress_bar=progress_bar,
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 188, in <lambda>
    self.study.optimize(lambda trial: _objective(self, trial, X, y),
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 128, in _objective
    raise RuntimeError(f"Optuna execution error: {self.function}")
RuntimeError: Optuna execution error: pta.stochrsi(X.close, length=trial.suggest_int('length', 2, 30), k=trial.suggest_int('k', 2, 30), d=trial.suggest_int('d', 2, 30), )
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-12-b484b4113d51> in <module>()
     27     ranges=[(2, 30)],
     28     trials=100,
---> 29     early_stop=50,
     30 )
     31 

2 frames
/usr/local/lib/python3.7/dist-packages/multiprocess/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

RuntimeError: Optuna execution error: pta.stochrsi(X.close, length=trial.suggest_int('length', 2, 30), k=trial.suggest_int('k', 2, 30), d=trial.suggest_int('d', 2, 30), )

**Comment by jmrichardson** [comment]
Hmmm. I am not able to reproduce on my end:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 123, in _objective
res = [eval_res(X, self.function, self.idx, trial, sym=sym) for sym, X in X.groupby(level=1)]
File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 123, in
res = [eval_res(X, self.function, self.idx, trial, sym=sym) for sym, X in X.groupby(level=1)]
File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 98, in eval_res
res = eval(function)
File "", line 1, in
File "/usr/local/lib/python3.7/dist-packages/pandas_ta/momentum/smi.py", line 23, in smi
tsi_df = tsi(close, fast=fast, slow=slow, signal=signal, scalar=scalar)
File "/usr/local/lib/python3.7/dist-packages/pandas_ta/momentum/tsi.py", line 34, in tsi
tsi_signal = ma(mamode, tsi, length=signal)
File "/usr/local/lib/python3.7/dist-packages/pandas_ta/overlap/ma.py", line 73, in ma
else: return ema(source, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/pandas_ta/overlap/ema.py", line 22, in ema
ema = EMA(close, length)
File "/usr/local/lib/python3.7/dist-packages/talib/init.py", line 35, in wrapper
result = func(*args, **kwargs)
File "talib/_func.pxi", line 2931, in talib._ta_lib.EMA
File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN
```
The above error is saying that the inputs are all NaNs?  Tuneta requires the dataset to have date/symbol as the index and ohlcv.  Is your dataset the same format?

And this:

`RuntimeError: Optuna execution error: pta.smi(X.close, fast=trial.suggest_int('fast', 2, 30), slow=trial.suggest_int('slow', 2, 30), signal=trial.suggest_int('signal', 2, 30), scalar=trial.suggest_int('scalar', 2, 30), )`

There seems to be an issue with running pta.smi   Unfortunately, i can't see what the error message is from pandas-ta. 

I just tried a bunch of different parameter combinations for pta.smi and all completed successfully.  I also have run a bunch of tests with 'all' and just those 3 indicators and no issue:

```
    tt.fit(X_train, y_train,
        indicators=['pta.stochrsi', 'pta.tsi', 'pta.smi'],
        # indicators=['all'],
        ranges=[(2, 30)],
        trials=100,
        early_stop=50,
    )
```

I just added some try/except logic to output the specific error message to see if that sheds some light on the situation.  Try installing with:

pip install -U git+https://github.com/jmrichardson/tuneta

Also, can you send me what your X_train dataframe looks like to see if there is anything there that could be causing the problem?

**Comment by jmrichardson** [comment]
Thinking more about the bfill, I am wondering if there is an issue where the indicators don't like data which begins with constant values?  Maybe remove those stocks and run again just as a test?
